# Generated by Django 4.2.2 on 2024-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Содержимое статьи"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/photo"),
                ),
                (
                    "view_count",
                    models.IntegerField(verbose_name="Количество просмотров"),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
