# Generated by Django 4.2.2 on 2024-09-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_date",
                    models.DateTimeField(
                        verbose_name="Дата и время последней попытки рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pos", "Успешно"), ("neg", "Не успешно")],
                        default="pos",
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True, null=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытки рассылки",
                "verbose_name_plural": "Попытки расылки",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=150, verbose_name="контактный email"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_mail",
                    models.CharField(max_length=150, verbose_name="Тема письма"),
                ),
                ("bode_mail", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        verbose_name="дата начала рассылки (первая рассылка)"
                    ),
                ),
                (
                    "periodic",
                    models.CharField(
                        choices=[
                            ("day", "Раз в день"),
                            ("week", "Раз в неделю"),
                            ("month", "Раз в месяц"),
                        ],
                        default="day",
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("create", "Создана"),
                            ("start", "Запущена"),
                            ("stop", "Завершена"),
                        ],
                        default="create",
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания расылки"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_sender.attempt",
                        verbose_name="Информация о попытке рассылки",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="email_sender.client",
                        verbose_name="Клиенты для которых рассылка",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_sender.message",
                        verbose_name="Сообщение для рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылки",
            },
        ),
    ]
