# Generated by Django 4.2.2 on 2024-09-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="email_sender.message",
                verbose_name="Сообщение для рассылки",
            ),
        ),
    ]
