# Generated by Django 4.2.2 on 2024-09-15 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_sender", "0002_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="email_sender.message",
                verbose_name="Сообщение для рассылки",
            ),
        ),
    ]
