# Generated by Django 4.2.2 on 2024-09-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_sender", "0003_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="email_sender.attempt",
                verbose_name="Информация о попытке рассылки",
            ),
        ),
    ]
