# Generated by Django 4.2.2 on 2024-09-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_sender", "0004_alter_mailing_attempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="attempt",
        ),
        migrations.AddField(
            model_name="attempt",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="email_sender.mailing",
                verbose_name="попытка рассылки",
            ),
        ),
    ]
