# Generated by Django 4.2.2 on 2024-09-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_sender", "0009_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_off_mailing", "can off mailing"),
                    ("cant_edit_mailing", "can edit mailing"),
                    ("cant_change_list_mailing", "cant change list mailing"),
                    ("cant_edit_mailing_message", "cant edit mailing message"),
                    ("can_view_mailing", "can view mailing"),
                    ("can_view_user_list", "can view user list"),
                ],
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылки",
            },
        ),
    ]
